# Generated by Django 4.0.6 on 2022-07-27 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0003_remove_service_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='service',
            name='titulo',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='uploaded',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
