# Generated by Django 4.0.6 on 2022-07-27 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0004_service_created_service_image_service_titulo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='created',
        ),
        migrations.RemoveField(
            model_name='service',
            name='uploaded',
        ),
    ]
