# Generated by Django 4.0.6 on 2022-07-27 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0005_remove_service_created_remove_service_uploaded'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='uploaded',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
