# Generated by Django 4.0.6 on 2022-07-27 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0006_service_created_service_uploaded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='uploaded',
            field=models.DateField(auto_now_add=True),
        ),
    ]
